### ISSUE TITLE
Error when exporting hierarchical decks

### ISSUE THREAD

**Issue by Malam9** [Pradhyo/anki-markdown-notes#10]
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2022-01-31 11:46:14

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\2141874715\__init__.py", line 317, in exportNotesUI
    exportedDecks = exportAllNotes(NotesPath)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\2141874715\__init__.py", line 279, in exportAllNotes
    os.makedirs(deckFolder)
  File "os.py", line 221, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:/Users/User/Documents/Obsidian/Vault/Notes\\Notes\\Default::Nested

I think what's going on is that nested decks are named "parent::deckname", but windows doesn't allow colons in filenames.
So when you set `deckFolder` to `os.path.join(NotesPath, deck)` where `deck` has double colons, everything is fine. But in the next line when you try to create a folder with that name, Windows forbids that and the error is thrown.

This is the exportAllNotes function that the bug is in:
```python
def exportAllNotes(NotesPath):
    """
    Exports all notes to markdown files in a Notes folder in 'NotesPath'.
    Aborts if 'Notes' folder already exists.
    For deck 'DeckName', a folder 'DeckName' is created and all the notes
    in that deck are stored in 'DeckName.md' in that folder.
    """
    showInfo("Logs are located here - " + directory)
    NotesPath = os.path.join(NotesPath, "Notes")
    if os.path.exists(NotesPath):
        showInfo("Aborting - 'Notes' folder already exists")
        return

    os.makedirs(NotesPath)
    allDecks = mw.col.decks.allNames()
    for deck in allDecks:
        deckFolder = os.path.join(NotesPath, deck)
        os.makedirs(deckFolder)
        with open(os.path.join(deckFolder, deck + ".md"), "w") as deckFile:
            deckFile.write("# {} \n\n".format(deck))
            for cid in mw.col.findNotes("deck:" + deck):
                note = mw.col.getNote(cid)
                writeNote(note, deckFile)

    return allDecks`

**Comment by Malam9** [comment]
You should use something like `deck = deck.replace('::','__')` or `deck = deck.replace('::','\\')`

**Comment by Pradhyo** [comment]
@Malam9 thanks for taking the time to report and provide a solution for this bug, will update when I can and close this!
