### ISSUE TITLE
ASCII codec error when exporting notes to Markdown

### ISSUE THREAD

**Issue by alexcthompson** [Pradhyo/anki-markdown-notes#5]
Hi @Pradhyo - thanks for creating and maintaining this add on.  I ran into a fail when trying to export my existing decks to Markdown.  Here's the error:

```python
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/alexcthompson/Library/Application Support/Anki2/addons/anki-markdown.py", line 271, in exportNotesUI
    exportedDecks = exportAllNotes(NotesPath)
  File "/Users/alexcthompson/Library/Application Support/Anki2/addons/anki-markdown.py", line 238, in exportAllNotes
    writeNote(note)
  File "/Users/alexcthompson/Library/Application Support/Anki2/addons/anki-markdown.py", line 226, in writeNote
    deckFile.write("A: {}\n".format(note.fields[1].replace("<br>", "\n")))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 198-199: ordinal not in range(128)
```
I think we're dealing with a classic Python unicode problem here.  My hunch, having done absolutely zero investigation is that `L226` in `anki-markdown.py`, by creating a format string, is casting some unicode characters to utf-8 badly, creating this error.  Using my Stackoverflow spidey sense, I wonder if [this answer might resolve the issue.](https://stackoverflow.com/a/9942885)

**Comment by alexcthompson** [comment]
My hunch is it comes from this card, the front of which reads `LDAP`.  The back contains the following copy paste pronunciation guide - `(LDAP; /ˈɛldæp/)` - from the Wikipedia article on LDAP.  I'm betting it's those special characters.

I've been messing with `anki-markdown.py` to see if I can set up logging and get that going well enough to debug.

Here's the full back of that card:

```Lightweight Directory Access Protocol

Used in integrations, though I don't know precisely how.

The Lightweight Directory Access Protocol (LDAP; /ˈɛldæp/) is an open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network.[1] Directory services play an important role in developing intranet and Internet applications by allowing the sharing of information about users, systems, networks, services, and applications throughout the network.[2] As examples, directory services may provide any organized set of records, often with a hierarchical structure, such as a corporate email directory. Similarly, a telephone directory is a list of subscribers with an address and a phone number.

LDAP is specified in a series of Internet Engineering Task Force (IETF) Standard Track publications called Request for Comments (RFCs), using the description language ASN.1. The latest specification is Version 3, published as RFC 4511. For example, here is an LDAP search translated into plain English: "Search in the company email directory for all people located in Nashville whose name contains 'Jesse' that have an email address. Please return their full name, email, title, and description."[3]

A common usage of LDAP is to provide a "single sign on" where one password for a user is shared between many services, such as applying a company login code to web pages (so that staff log in only once to company computers, and then are automatically logged into the company intranet).[3]

LDAP is based on a simpler subset of the standards contained within the X.500 standard. Because of this relationship, LDAP is sometimes called X.500-lite.[4]```

**Comment by alexcthompson** [comment]
Added some code to allow import and export of notes with unicode characters, will fork and submit a PR tomorrow.
