### ISSUE TITLE
ImportError: No module named glob

### ISSUE THREAD

**Issue by nocibambi** [Pradhyo/anki-markdown-notes#7]
I installed the plugin through Anki's own specific menu. Since then, I receive the following error message each time I open Anki:

> An error occurred in an add-on.
> Please post on the add-on forum:
> https://anki.tenderapp.com/discussions/add-ons
> 
> ```python
> Traceback (most recent call last):
>   File "aqt/addons.py", line 41, in loadAddons
>   File "/home/andras/.local/share/Anki2/addons/Anki_Markdown_Notes.py", line 6, in <module>
>     from glob import glob
> ImportError: No module named glob
> ```

It has been already reported here: https://anki.tenderapp.com/discussions/add-ons/16903-error-with-markdown-addon

I checked, and I have `glob2` installed:

```bash
>>> ~$ pip list | grep glob
glob2                              0.6
```

Neither the following console command yields any error:
```py
from glob import glob
```

**Comment by Pradhyo** [comment]
Thanks for raising this. Somehow I haven't encountered this.
Based on the [docs](https://apps.ankiweb.net/docs/addons.html#standard-modules) I'd have to include the glob code. I will take care of this when I get a chance.
